export const DASHBOARD_MENU_CODE = "1"
export const IMPORT_DATA_MENU_CODE = '104';
export const SUPERVISORS_MENU_CODE = '101';
export const PROVIDERS_MENU_CODE = '105';
export const CONSULT_MENU_CODE = '103';
export const ACTIVATOR_MENU_CODE = '102';
export const QA_MENU_CODE = '106';
export const IMPORT_INVENTORY_MENU_CODE = '107';
export const INVENTORY_MENU_CODE = '108';

export const REPORTS_GENERAL_MENU_CODE = "3"
export const REPORTS_MENU_CODE = '301';

export const MASTERS_MENU_CODE = "4"
export const MASTERS_RETURNS_MENU_CODE = '401';
export const MASTERS_DOCUMENTS_MENU_CODE = '402';
export const MASTERS_ERRORS_MENU_CODE = '403';
export const MASTERS_OFFICERS_MENU_CODE = '404';
export const MASTERS_PRODUCTS_MENU_CODE = '405';
export const MASTERS_PROCEDURES_MENU_CODE = '406';
export const MASTERS_PROVIDERS_MENU_CODE = '407';
export const MASTERS_PROVIDERS_ZONE_MENU_CODE = '408';
export const MASTERS_CALENDAR_MENU_CODE = '409';
export const MASTERS_BRANCHOFFICES_MENU_CODE= '410';

export const ASSIGNMENT_MENU_CODE = "5"
export const PERIOD_TIME_MENU_CODE = '501';
export const COMISSION_GROUP_MENU_CODE = '502';
export const OFFICERS_ASSIGNMENT_MENU_CODE = '503';
export const COMISSIONS_PROVIDER_MENU_CODE = '504';

export const COMISSIONS_GENERAL_MENU_CODE = "6"
export const COMISSIONS_PROVIDER_2_MENU_CODE = '601';